### PR TITLE
Made a homepage for YouTube webpage, added index.html and style.css. Added a README file.

### PR DESCRIPTION
**Pull request by abrormukimov**
This is a sample YouTube homepage. We have worked on this project using html and css.

### CODE REVIEW

**Comment by majovanilla** [comment]
Hey @abrormukimov and @JelilFaisalAbudu , 👋

Your project is looking better every time!

However I want to address a **VERY IMPORTANT** issue here, before moving on with the review.

**First of all, your git flow needs to be organized.**
The correct way to work on your projects is something like this:
- You create a repo
- You add the readme file
- You create a new branch with a descriptive name
- You work on that branch UNTIL your project is approved
- The LAST step is merging into master

**Secondly, you don't have to open and close multiple Pull Requests**
You need to open JUST ONE pull request and do all the required changes on your project and then send the SAME link of the pull request until it is approved. 
This way, everyone has a continuity of the required changes and can do a better job.

**Now, the code review**

There are still some changes 👇 you need to implement to approve this request 🔍 based on the other code reviews that my colleagues did and the requirements of the project: 
https://github.com/abrormukimov/youtubeclone/pull/4
https://github.com/abrormukimov/youtubeclone/pull/7


### Required Changes: ✍️

- Your pull request message is not descriptive of the work you did. See this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) to know how to make a good pull request message.

- You need to check the HTML validator. You have multiple errors and warnings. Check it [here](https://validator.w3.org/nu/?doc=https%3A%2F%2Fgithub.com%2Fabrormukimov%2Fyoutubeclone%2Fblob%2Fhomepage%2Findex.html)

- The nav icons should be on the right-most side of the page.

Yours:

Screenshot from 2020-02-21 04-49-12

Original:

Screenshot from 2020-02-21 04-49-20

- You have some overlapping elements on your page. Please take care of them so they are displayed properly. See screenshots below:

Screenshot from 2020-02-21 04-36-21
Screenshot from 2020-02-21 04-36-33
Screenshot from 2020-02-21 04-36-42



### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- You are still missing the comment section. You can include only one or two mock comments to display it.

- You could use the same icons on the original page navbar to make your project look better.

## Please, make all REQUIRED changes and submit your request again using THE SAME Pull Request! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but we need to fix the issues below before moving on ⬇️

- [ ] The nav icons should be on the right-most side of the page.



[OPTIONAL]

- [ ] Consider be descriptive on which changes you made on your commit, for example, you commit: "Add some minor changes" consider explain which minor changes you made.

As @majovanilla recommend you, I think this is important to show your project in the future:

- [ ] You are still missing the comment section. You can include only one or two mock comments to display it.

- [ ] You could use the same icons on the original page navbar to make your project look better.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by abrormukimov** [comment]
Hi Maria!
As I can see in instructions given on the website theodinproject.com we
shouldn't have a comment section. And about the icons we used in the
navbar: we are just at the beginning of our studies and we don't have a
good previous background info about html and css!
Please, approve our project for now so we can move forward to be able to
work on the next projects. We will do our best to learn everything first
and provide more advanced codes in our projects later.

Thank you a lot Maria,

Sincerely,

Abror Mukimov

**Comment by majovanilla** [comment]
Hi @abrormukimov !

Yes, I know that the comment section is not mandatory, that's why I included it in the [OPTIONAL] requirements. :heavy_check_mark: 

About the icons, I know you are just starting, that's why we always include [OPTIONAL] tips so that you get better every time :muscle:  So it's not about rushing into the program but achieving mastering. :medal_sports: 

If you submitted your project again, then a TSE will review it and see if you met the REQUIRED changes and approve your project. So don't worry! :crossed_fingers:

**Pull request closed without merging**
